"""Migration-chain integrity tests (the CI gate behind "models and
migrations may never drift").

All tests here are deliberately SYNC: migrations/env.py drives the async
engine via asyncio.run(), which cannot be nested inside an already-running
event loop — pytest-asyncio's auto mode leaves plain `def` tests on the
main thread with no loop, exactly what alembic needs.
"""

import asyncio
import contextlib
from pathlib import Path

import pytest
from alembic import command
from alembic.config import Config
from sqlalchemy import create_engine, inspect

from app.config import get_settings
from app.db.models import Base

PROJECT_ROOT = Path(__file__).resolve().parent.parent


@pytest.fixture
def alembic_cfg(monkeypatch, tmp_path):
    db_path = tmp_path / "migrations_test.db"
    url = f"sqlite+aiosqlite:///{db_path.as_posix()}"
    monkeypatch.setenv("DATABASE_URL", url)
    get_settings.cache_clear()

    cfg = Config(str(PROJECT_ROOT / "alembic.ini"))
    cfg.set_main_option("script_location", str(PROJECT_ROOT / "migrations"))

    yield cfg, db_path

    get_settings.cache_clear()


def _inspect_schema(db_path: Path) -> dict[str, set[str]]:
    """table -> column names, via a plain sync engine (inspection only)."""
    engine = create_engine(f"sqlite:///{db_path.as_posix()}")
    try:
        inspector = inspect(engine)
        return {
            table: {c["name"] for c in inspector.get_columns(table)}
            for table in inspector.get_table_names()
            if table != "alembic_version"
        }
    finally:
        engine.dispose()


def test_upgrade_head_builds_every_model_table(alembic_cfg):
    cfg, db_path = alembic_cfg
    command.upgrade(cfg, "head")

    schema = _inspect_schema(db_path)
    for table in Base.metadata.tables:
        assert table in schema, f"migrations never create table {table!r}"
        model_columns = {c.name for c in Base.metadata.tables[table].columns}
        missing = model_columns - schema[table]
        assert not missing, f"table {table!r} is missing columns {missing} after upgrade head"


def test_no_drift_between_head_and_models(alembic_cfg):
    """alembic check == "autogenerate found nothing to do" — the exact
    condition that breaks when someone edits app/db/models.py without
    cutting a migration. This is the test that makes migrations impossible
    to forget.
    """
    from alembic.util.exc import AutogenerateDiffsDetected

    cfg, _ = alembic_cfg
    command.upgrade(cfg, "head")
    try:
        command.check(cfg)
    except AutogenerateDiffsDetected as exc:
        pytest.fail(
            "app/db/models.py has schema changes with no matching migration — "
            f"run `alembic revision --autogenerate -m '<what changed>'`. Diffs: {exc}"
        )


def test_alembic_and_init_db_agree(alembic_cfg, tmp_path, monkeypatch):
    """The two schema-creation paths (alembic upgrade head vs init_db()'s
    create_all + _ensure_column) must produce identical table/column sets —
    a deployment switching between them must never see a schema difference.
    """
    cfg, alembic_db = alembic_cfg
    command.upgrade(cfg, "head")
    alembic_schema = _inspect_schema(alembic_db)

    initdb_path = tmp_path / "initdb_test.db"
    monkeypatch.setenv("DATABASE_URL", f"sqlite+aiosqlite:///{initdb_path.as_posix()}")
    get_settings.cache_clear()

    from app.db import session as db_session_module

    db_session_module._engine = None
    db_session_module._session_factory = None
    try:
        asyncio.run(db_session_module.init_db())
        # Dispose the async engine inside the same loop that created it.
        engine = db_session_module.get_engine()
        with contextlib.suppress(Exception):
            asyncio.run(engine.dispose())
    finally:
        db_session_module._engine = None
        db_session_module._session_factory = None
        get_settings.cache_clear()

    initdb_schema = _inspect_schema(initdb_path)

    assert alembic_schema.keys() == initdb_schema.keys()
    for table, columns in alembic_schema.items():
        assert columns == initdb_schema[table], (
            f"table {table!r} differs between alembic and init_db paths: "
            f"only-alembic={columns - initdb_schema[table]}, "
            f"only-initdb={initdb_schema[table] - columns}"
        )
