"""app access grants

Revision ID: 833aa5c09528
Revises: bf77a10c66d1
Create Date: 2026-07-21 18:28:26.368798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '833aa5c09528'
down_revision: Union[str, None] = 'bf77a10c66d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_access_grants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('app_name', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'REVOKED', name='appaccessstatus'), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('granted_by_ticket_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['granted_by_ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('app_access_grants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_app_access_grants_app_name'), ['app_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_app_access_grants_username'), ['username'], unique=False)
    # ### end Alembic commands ###
    #
    # NOTE: autogenerate also proposed dropping employee_users.created_at/
    # updated_at here. That's PRE-EXISTING drift between initial_schema.py
    # (which creates those two columns) and the current EmployeeUser model
    # (which has never declared them, verified via git blame/log — not
    # something this migration's own changes caused). Deliberately NOT
    # included: this migration's job is adding app_access_grants, not
    # silently dropping two columns from a live production table as a side
    # effect of an unrelated feature. That drift is real and worth its own
    # investigated, reviewed migration — tracked separately, not bundled
    # here where it could ship unreviewed.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('app_access_grants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_app_access_grants_username'))
        batch_op.drop_index(batch_op.f('ix_app_access_grants_app_name'))

    op.drop_table('app_access_grants')
    # ### end Alembic commands ###
