"""initial schema

Revision ID: 42de869b6fed
Revises: 
Create Date: 2026-07-13 13:10:07.799414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '42de869b6fed'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'STANDARD', name='apiclientrole'), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('daily_request_limit', sa.Integer(), nullable=False),
    sa.Column('daily_request_count', sa.Integer(), nullable=False),
    sa.Column('request_count_reset_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_last_purged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_clients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_clients_key'), ['key'], unique=True)
        batch_op.create_index(batch_op.f('ix_api_clients_name'), ['name'], unique=True)

    op.create_table('idempotency_keys',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('response_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('reviewers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('role', sa.Enum('IT_ADMIN', 'MANAGER', name='reviewerrole'), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('telegram_chat_id', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reviewers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reviewers_telegram_chat_id'), ['telegram_chat_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_reviewers_token'), ['token'], unique=True)
        batch_op.create_index(batch_op.f('ix_reviewers_username'), ['username'], unique=True)

    op.create_table('employee_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('department', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'DISABLED', name='userstatus'), nullable=False),
    sa.Column('access_grants', sa.JSON(), nullable=False),
    sa.Column('manager_username', sa.String(length=64), nullable=False),
    sa.Column('owned_by_client_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owned_by_client_id'], ['api_clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('employee_users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_employee_users_username'), ['username'], unique=True)

    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester', sa.String(length=128), nullable=False),
    sa.Column('subject', sa.String(length=256), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('RECEIVED', 'PLANNING', 'AWAITING_APPROVAL', 'EXECUTING', 'COMPLETED', 'REJECTED', 'FAILED', name='ticketstatus'), nullable=False),
    sa.Column('result_summary', sa.Text(), nullable=False),
    sa.Column('submitted_by_client_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['submitted_by_client_id'], ['api_clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('approvals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('tool_name', sa.String(length=64), nullable=False),
    sa.Column('tool_args', sa.JSON(), nullable=False),
    sa.Column('reasoning', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'ESCALATED', name='approvalstatus'), nullable=False),
    sa.Column('reviewer', sa.String(length=128), nullable=False),
    sa.Column('reviewer_auth_method', sa.String(length=16), nullable=True),
    sa.Column('reviewer_oidc_subject', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sla_deadline', sa.DateTime(timezone=True), nullable=False),
    sa.Column('escalated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=True),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('tool_name', sa.String(length=64), nullable=False),
    sa.Column('tool_args', sa.JSON(), nullable=False),
    sa.Column('result', sa.Text(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit_log')
    op.drop_table('approvals')
    op.drop_table('tickets')
    with op.batch_alter_table('employee_users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_employee_users_username'))

    op.drop_table('employee_users')
    with op.batch_alter_table('reviewers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reviewers_username'))
        batch_op.drop_index(batch_op.f('ix_reviewers_token'))
        batch_op.drop_index(batch_op.f('ix_reviewers_telegram_chat_id'))

    op.drop_table('reviewers')
    op.drop_table('idempotency_keys')
    with op.batch_alter_table('api_clients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_clients_name'))
        batch_op.drop_index(batch_op.f('ix_api_clients_key'))

    op.drop_table('api_clients')
    # ### end Alembic commands ###
